### ISSUE TITLE
Compile error. Check my Screenshot

### ISSUE THREAD

**Issue by saianwork** [krijnsent/crypto_vba#1]
![image](https://user-images.githubusercontent.com/31490998/31395266-aa13d8e2-ade0-11e7-8111-83c35c67d30e.png)

Can you make some steps on how to get started. It's really not clear please.

thanks for you work.

**Comment by krijnsent** [comment]
Thanks for the feedback. I pushed a new version which should work. This error is probably caused by the way I update my example file, which should be correct now (manually checked it).

**Comment by krijnsent** [comment]
Seems to work for saianwork, closing issue
