### ISSUE TITLE
SAME ISSUE still exist -1100 Illegal characters found in parameter 'timestamp'; legal range is '^[0-9]{1,20}$'.

### ISSUE THREAD

**Issue by deciBel1982** [krijnsent/crypto_vba#10]
Hello Koen,

I saw you updated the following line:
NonceUnique = Trim(Str((Val(NonceUnique) + TimeCorrection)) & Right(Timer * 100, 2) & "0")
However, after midnight, still the same issue occurs relating these invalid caracters.
Any other suggestions?
Thanks.

Kind regards

**Comment by rexii2300** [comment]
I have the same error when I run this after midnight. on GMT+11 here, I also had to use TimeCorrection = -39600 to align timestamp.

**Comment by krijnsent** [comment]
Thanks for the feedback, could any of you email me/post here what Url is used?
In the Binance module there is this line:
Url = TradeApiSite & Method & "?" & postdata & "&signature=" & APIsign
If you could add and post the result here:
Debug.print Url
Thanks in advance!

**Comment by rexii2300** [comment]
i get

https://api.binance.com/api/v3/account?&timestamp=1515590143.80&signature=xxxxxxxxxxxxxxxxxxxx

ran about 2min ago. i've hidden the signature, not sure if it's sensitive.

thanks for the awesome vba, saving me so much time!

**Comment by krijnsent** [comment]
Okay, I see the problem: there is a dot (.) in the timestamp (there was a space in the previous error). Will try to push an update out in a little.
The signature is not sensitive: it's a hash, so there is no way for anyone to see what went into it.

**Comment by balin77** [comment]
Hey krijnsent, 
your connections to all the exchanges are great. I have tested the Bittrex and Binance connections and both are working fine now. I had the same problem with the dots and solved it like this:

`NonceUnique = GetTimeBinance

Function GetTimeBinance() As Double

Dim JsonResponse As String
Dim Json As Object
'-> normally JSON is returned like {}, a dictionary in VBA,
'-> some functions return JSON is returned like [], a collection in VBA
'-> so to catch both, Dim Json as Object
Dim JsonRes As Dictionary
Dim apikey As String
Dim secretkey As String

'PublicBinance time
JsonResponse = PublicBinance("v1/", "time")
Set Json = JsonConverter.ParseJson(JsonResponse)
ResArr = JsonToArray(Json)
tbl = ArrayTable(ResArr)
GetTimeBinance = tbl(1, 2)

End Function`

I just ask Binance first for their public servertime and send it back to them again.

**Comment by krijnsent** [comment]
Good one, I thought of it before, but never got to include it. Might include it in my project as an option for Binance!
