### ISSUE TITLE
Please add HitBTC

### ISSUE THREAD

**Issue by coinyguys** [krijnsent/crypto_vba#12]
Could you please add HitBTC and can you give any example to import open orders and cancel / place the order.

**Comment by krijnsent** [comment]
Will try, have an account with them, so should be doable. No clue when I'll get to it, but will do my best.

**Comment by coinyguys** [comment]
Thanks buddy,

I'll very much delighted that you considered my suggestion.
BTW, during searching of vba project, somewhere i got some codes to fetch
BITTREX API in excel sheet, including open orders, balance, account history.
I was trying to place the order but didn't successful.
May be you knew those codes.
I'm not a developer of those codes, neither a software engineer.
To run those codes, your json script is also essential.

If you required, I'll share the module files with you.


Take care.
Bye.
Sudhakar.



On Jan 14, 2018 20:56, "Koen Rijnsent" <notifications@github.com> wrote:

Will try, have an account with them, so should be doable. No clue when I'll
get to it, but will do my best.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/krijnsent/crypto_vba/issues/12#issuecomment-357519165>,
or mute the thread

**Comment by krijnsent** [comment]
Hi @coinyguys , I just added HitBTC. This project is not to build an Excel tool to connect to exchanges, but rather a collection of connectors. If you want a full-fledged Excel tool you'd have to code it yourself (for now, I'm considering building one, but that won't be soon).
