### ISSUE TITLE
Cryptopia: API incapsulation erro

### ISSUE THREAD

**Issue by tconrado** [krijnsent/crypto_vba#13]
Hi, I tried in the past to use the Cpryptopia API on excel but had no success.
You may have the same issue, and I really want to help to be able to use cryptopia on excel...
The only hint that I found about the error was:

https://social.technet.microsoft.com/Forums/en-US/b10b16d1-8eea-4b52-8aeb-f96ea87135fa/sectionresponseheader-detailcr-must-be-followed-by-lf?forum=powerquery 

please, let me know if you were able to pull market data from cryptopia to excel 

regards,

**Comment by krijnsent** [comment]
Hi, did you use the code in my project? I put a Cryptopia example in the Excel file, you could try that one to get your balances.

**Comment by tconrado** [comment]
Well, I tried, but it did not work... it does have a message "Working on it" so I assumed that you did not finished it... Other market show as expected...

**Comment by krijnsent** [comment]
@tconrado Please check the latest Excel sample file in this project. The examples I have in my projects are all simple ones that can help you to code the VBA for e.g. orderbooks, making a trade etc. By no means is it my purpose right now to have an Excel/VBA toolkit that covers 100% of the API. Hope the code helps you!
