### ISSUE TITLE
Bithumb

### ISSUE THREAD

**Issue by theMoe** [krijnsent/crypto_vba#15]
Hey,

have you thought about the API of Bithumb.com?

Bye

Moe

**Comment by krijnsent** [comment]
Hi Moe, I tried to subscribe to Bithumb a couple of times, but keep getting some weird error. Will try again soonish.

**Comment by krijnsent** [comment]
Over a month later, can't get an account on Bithumb, still get the same "Array" error.

**Comment by krijnsent** [comment]
Ticket check: still looking for me to add Bithumb ?
