### ISSUE TITLE
Porting your code .NET

### ISSUE THREAD

**Issue by muteddisk** [krijnsent/crypto_vba#18]
Hi,

I was trying to port your code to .NET. I started with Binance. I can't get my head around how to make the signature. I always get a message saying Invalid API key. Obviously, I have a api key. the work fine under linux with python. So I know the key works. Can you give me a hand with it?

**Comment by krijnsent** [comment]
Hi @muteddisk , my .NET is a bit rusty and I don't have dev tools installed, but do throw the code my way, I can try and see if I can spot what's wrong.
