### ISSUE TITLE
Add Kucoin tab in the crypto_vba_example.xlsm workbook

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#19]
Hi krijnsent,

First of all, a big thanks for all the work you have been doing here, this is super helpful and saving me a lot of time! I have sent you a little contribution to your BTC address as a mark of my gratitude :)

I have been using your spreadsheet/code for a week now and I have a few feature requests I would like to ask. I will create a separate ticket for each, so your GitHub stays clean.

Starting with an easy one: I see you have added the code to import data from Kucoin yesterday, but there is currently no Kucoin tab in the example workbook. Can you please add one tab similar to the other ones (e.g. Bittrex), to make easy it to import private portfolio data from Kucoin?

I hope you will continue to have time to further improve your spreadsheet and that people will keep supporting you!

All the best,
Pierre

**Comment by krijnsent** [comment]
Hi Pierre, first of all thanks for all the beer/coffee you sent! I am working on a more full-fledged Excel tool for users that don't speak VBA that well, but that's still in the making. Do send me an email (info@ my websitename), then I can pass you a prototype.

**Comment by Pi-Rr** [comment]
Hi krijnsent, thanks a lot, I will email you :)

**Comment by krijnsent** [comment]
Added an example for Kucoin, please check and open a new issue if it doesn't work.
