### ISSUE TITLE
Make Kraken code import current portfolio balances instead of deposit history

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#20]
Hi again krijnsent,

Here is my second feature request. The Kraken tab in the example workbook is currently importing the deposit history when running the GetMyKrakenData macro. Could you please make it import the latest private portfolio balances instead (e.g. similar to what the Bittrex or Binance tabs do).

Many thanks,
Pierre

**Comment by krijnsent** [comment]
Updated the code.

**Comment by Pi-Rr** [comment]
Thank you very much, Kraken works perfectly now 👍
