### ISSUE TITLE
Import wallet balances from Etherscan or a similar blockchain explorer

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#21]
Hi there,

Here is my third feature request. Would it be possible to develop some code to import the balances of a wallet (ETH and any other token) directly from a public key? Maybe that’s possible using the [Etherscan api](https://etherscan.io/apis), or the one of any other blockchain explorer?

Many thanks,
Pierre

**Comment by krijnsent** [comment]
Have thought about this and started a project for it. The code is not that workable/presentable yet, so keep an eye on that project: https://github.com/krijnsent/my_wallets_vba

**Comment by Pi-Rr** [comment]
Super, I'll monitor that closely. Good luck with putting it together!
