### ISSUE TITLE
Import historical price and volume data from Kraken

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#22]
Hi again,

Here is my last feature request (it was a lot!). Would it be possible to develop some code to import the historical prices and volumes from Kraken for any given pair available on the exchange?
Ideally, the user will have to input three things:
1) The pair he is interested in (e.g. ETH/EUR, XRP/BTC, etc.)
2) The desired time interval between each prices (e.g. 5 minutes, 1 hour, etc.)
3) The desired period to cover (e.g. last 6 months, from 01-Jan-2017 to 31-Dec-2017, etc.)

If you think you could help with that, it would be amazing :)

Dank u wel!
Pierre

**Comment by krijnsent** [comment]
Hi Pierre, thanks for the direction of thought! I have some simple version of this running locally, but it's buggy as can be. Will try to come up with a good location for this code (in this project or in another).

**Comment by Pi-Rr** [comment]
Great, glad to hear that you started that already :)

**Comment by Pi-Rr** [comment]
Hi Koen,

The functions I tested work well (though make the spreadsheet a bit unstable if too many are used in the same workbook, e.g. to recover historical prices over a long period of time). I am closing the ticket.

Thanks a lot!
Pierre
