### ISSUE TITLE
Kucoin only import the balance for 12 tokens

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#23]
Hi Koen,

Thanks a lot for adding Kucoin to the spreadsheet. The import of the balance works, but partially only.
I own a really small amount of a lot of different tokens on that exchange (due to the Kucoin (KCS) token paying to holders a small fraction of the transaction fees of any token traded on the platform). However, when I run the macro, it only pulls the data for 12 tokens, some of which are very random ones with a super small balance, and it is missing a bunch of the more significant ones.

Is that something you can fix?
I understand it might cause some performance issues to pull the data for every single token - in that case it is possible to prioritise the ones with the highest balance value?

Many thanks!

**Comment by krijnsent** [comment]
I found the solution: the KuCoin API will only give back a limited number of entries. If you have KCS you'll get a bunch of coins/tokens, all in small quantities.
ToDo: create a loop, pull from the JSON answer this part: "currPageNo":1,"limit":12,"pageNos":8 , and get the other pages too.

**Comment by krijnsent** [comment]
Please check the improved example, I included a loop to pull in all Kucoin balances. Do close this issue if it works for you.

**Comment by Pi-Rr** [comment]
Just tried it, it works perfectly now, thank you very much!
