### ISSUE TITLE
Kraken Error - EAPI:Invalid nonce

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#24]
Opening a new tickets for Kraken as the private balance download is not working consistently.
Sometime running the macro works perfectly, and sometime the Kraken Balance table return the following error: "EAPI:Invalid nonce".

I cannot figure out why it is happening, but if you wait and try again a bit later it works again. Not a critical issue therefore, but I wanted to flag it.

Thanks again for sharing your work!

**Comment by krijnsent** [comment]
Hi Pi-Rr, probably some invalid characters in the Nonce, I'll have to make sure that you always get "numbers only" (e.g. with Binance I had issue with a space and a dot popping up). Will work on the nonce generator.

**Comment by Pi-Rr** [comment]
Super, thank you!

**Comment by yvesbk** [comment]
Hi ! Many thanks forwritting this wonderfull code :-)

I have a problem to put an order to Kraken: the call of the method "AddOrder" return the error "EAPI:Invalid nonce", while the method "Balance works fine:

?PrivateKraken("AddOrder", apikey_kraken, secretkey_kraken, "?pair=XETHZEUR?type=sell?ordertype=market?volume=1")
{"error":["EAPI:Invalid nonce"]}

?PrivateKraken("Balance", apikey_kraken, secretkey_kraken)
{"error":[],"result":{"ZUSD":"0.1795",....

Do I have bad formatted the parameters for the AddOrder ? Or an other issue ?

Thanks in advance !

Yves

**Comment by yvesbk** [comment]
Tried with & instead of ? and still the same problem:

?pair=XETHZEUR&type=sell&ordertype=limit&price=800&volume=1

**Comment by yvesbk** [comment]
Found ! ok without a ? a the beginning and with a & at the end:

pair=XETHZEUR&type=sell&ordertype=limit&price=800&volume=1&

**Comment by krijnsent** [comment]
Hi, I just updated the version with a separate nonce function, hopefully this will solve this issue.

**Comment by yvesbk** [comment]
Thank you very much !

**Comment by Pi-Rr** [comment]
Thank you! It seems to be working all right now, I am closing the issue.
