### ISSUE TITLE
trading responses

### ISSUE THREAD

**Issue by incobart** [krijnsent/crypto_vba#26]
Hi,  would it be possible to put the trading options like buy sell cancel pls, I have some issues with Kucoin and Hitbtc
 thanks

**Comment by krijnsent** [comment]
Hi, I'll try to add examples for all exchanges, but am not sure when I'll get around to doing that.

**Comment by incobart** [comment]
Hi,
maybe this one can help to make the Kucoin working ? https://github.com/Satoshinaire/kucoin-api/issues or  http://python-kucoin.readthedocs.io/en/latest/kucoin.html  or https://github.com/sammchardy/python-kucoin or https://www.reddit.com/r/kucoin/comments/85gjv6/kucoin_python_api_help/  thanks

**Comment by krijnsent** [comment]
Have updated the code and included some examples for some exchanges, does that help enough?
