### ISSUE TITLE
Problem with Poloniex

### ISSUE THREAD

**Issue by Ezoptron** [krijnsent/crypto_vba#28]
Hello. I use Win7 SP1 and Excel 2010.
The solution, that was described in previous ticket is not working. 

set objHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")
objHTTP.Option(4) = 13056
objHTTP.Open "POST", Url, False

The same error is appeared.

**Comment by krijnsent** [comment]
Refers back to #25 , did you run all windows & office updates that were recommended?

**Comment by Ezoptron** [comment]
Of course

**Comment by krijnsent** [comment]
Mmm, weird. Sorry for not getting back to you sooner, I'm puzzled like you are. Will try to dig up some trick, but don't know what that would be. If you make any progress yourself, please do let me know.

**Comment by theMoe** [comment]
I would like to mention, that I fixed the problem with this Easy fix from Microsoft.

https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

And I also added objHTTP.Option...

Maybe this can help. But after the easy fix I got some proxy errors with Outlook.
