### ISSUE TITLE
run-time error 429 ActiveX component can't create object

### ISSUE THREAD

**Issue by accept1960** [krijnsent/crypto_vba#29]
I'm getting this error in Excel 2016 for Mac. I try to get information from Binance.

Don't know what is going wrong.

Please assist.

**Comment by krijnsent** [comment]
Hi, at what line does the code throw that error? The only reference I get with a global search for that error is that the objects need to be Defined/dimmed differently. Do the cryptocompare functions I created work as they should? I hope you can answer these questions, as that helps me helping you. Cheers!

**Comment by krijnsent** [comment]
Closed due to no response
