### ISSUE TITLE
iV=DictIn(k) error

### ISSUE THREAD

**Issue by henryvba** [krijnsent/crypto_vba#3]
Hey developer,

Thanks for creating such an useful tool.
I was trying to run the macro in the excel file on Kraken sheet and the vba stops at the line iV=Dictln(k). The error msg shows as 
"Run-time error '450':
Wrong number of arguments or invalid property assignment"

Do you know how I should overcome this?
Thanks

**Comment by krijnsent** [comment]
Hi Henry,
can you maybe pass me the info (API response) that makes that macro crash? See e.g. issue #2 for an example, that helped me solve it.
Thanks,
Koen

**Comment by krijnsent** [comment]
No response, closed. Please open a new issue if you have more info.
