### ISSUE TITLE
Problem with Kucoin - Run-time error '-2147012746 (80072f76)'

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#31]
Hi krijnsent,

Since approximately a week, I am getting a run-time error '-2147012746 (80072f76)' every time I try to update my balance for Kucoin.
The error occurs at line 70 of the PrivateKucoin function:

`objHTTP.setRequestHeader "KC-API-KEY", apikey`

It would be great if you could have a look when you get some time.

Many thanks!

**Comment by krijnsent** [comment]
Hi @Pi-Rr 
I got the same error the first time I tried, apparently the variable "apikey" is empty when the macro reaches that point. That variable should get picked up here: 
secretkey = Sht.Range("secretkey_kucoin").Value 
Bizarrely, I checked the reference and the cell and it seemed to be okay. So I ran the macro again and it worked like a charm. I'll keep on testing, but it did seem some weird fluke. Could you try checking the cell reference and maybe debug.print to confirm that the variable is empty when that function is called?

**Comment by Pi-Rr** [comment]
Hi krijnsent,
I managed to fixed the issue, it was not related to the code but to Kucoin (which make sense given it was working perfectly till recently). They changed some security settings with regard to the API and I had to connect on the platform and reactivate the API key. It's working like charm again, I will close the issue 👍 
Thanks :)
