### ISSUE TITLE
Binance connection problem

### ISSUE THREAD

**Issue by sbralin** [krijnsent/crypto_vba#33]
I ran VBA ModExchBinance/Sub TestBinance() but I got error, pls, advice: 
{"error_nr":-2147012739,"error_txt":"VBA-WinHttp.WinHttpRequest ?????? ????????? ?????????? ???????
"}

**Comment by krijnsent** [comment]
Hi @sbralin, it looks like this error: #25
Could you check out the solutions there and see if they work for you?

**Comment by krijnsent** [comment]
Cool! Happy to hear
