### ISSUE TITLE
Binance/Poloniex Historical Data Inaccurate (possibly all exchanges)

### ISSUE THREAD

**Issue by ITJusus** [krijnsent/crypto_vba#34]
I don't know if this is a known issue or not, but when pulling historical prices (via C_ARR_OHLCV method) the prices are way off from the actual exchange requested.  For example, when I utilize...

C_ARR_OHLCV("H", "RCN", "BTC", "EOHLC", "60", Now, "Binance")

And then I compare the outputted values to the actual charts on Binance or on TradingView (filtered as Binance)...the TradingView and official Binance site's chart values match perfectly to each other, but the values generated by Crypto_vba are often not even in the same candle range.  Sometimes I see the High price generated from Crypto_vba is below the entire candle itself (looking at Binance/TradingView)...like I said, way off.

Is all of this data being pulled from CryptoCompare and perhaps they are just ignoring the request for "Binance" or perhaps are they returning the wrong exchanges data?

**Comment by ITJusus** [comment]
I know this is a free offering / side project, so I don't expect immediate responses of course.  If someone could at least confirm for me, in the community or the author, that this issue is indeed a problem on the "CryptoCompare" side of things...I can then go raise this issue with them that they are pushing out inaccurate Binance historical price info.

**Comment by krijnsent** [comment]
Hi @ITJusus , that sounds weird. I'll try to get the same data from the Binance API, but it does indeed sound like a CryptoCompare issue. What you could do is debug.print the raw command that's used and copy-paste that in the browser, that should give you the exact JSON to compare with Binance.

**Comment by ITJusus** [comment]
Thank you.  I emailed info@cryptocompare.com and I also submitted a ticket to what appears to be the CryptoCompare API issue tracking site...

https://github.com/ccxt/ccxt/issues/2651

Please let us know if anyone on here figures out anything new about this and I'll let you know if CryptoCompare responds with anything meaningful as well.

**Comment by ITJusus** [comment]
I just tested using Crypto_VBA to get Poloniex based historical prices as well.  These numbers are not accurate to the TradingViewer/Poloniex charting numbers either.  So, this seems to be a wider issue with the historical data that is returned for multiple exchanges via CrypoCompare to Crypto_VBA.  Is this just me or are you getting the same results out there?

**Comment by krijnsent** [comment]
A brainfart: could it be that there is just a shift in the data (some hours different, maybe caused by timezones)?

**Comment by Pi-Rr** [comment]
Hello,

I have run some tests using the C_ARR_OHLCV (e.g. C_ARR_OHLCV("1H","RCN","BTC","TEOHLCFV",48,NOW(),"Binance") and compared to Binance charts and it all mach perfectly for me (except for the time which is 1h behind, but that's probably a local settings issue).

I also cross-checked with the "RATES_MACRO" tab that is available in the crypto_vba_example.xlsm file, and it matches too.

krijnsent, do you have the issue too?

**Comment by ITJusus** [comment]
The Test Binance sub you provided above matches Binance, once I align the timezone to UTC.  And then I started tracking back the results when I use...

C_ARR_OHLCV("1H","ZRX","BTC","EOHLCFV",60,NOW(),"Binance")

I found the pattern.  The results are exactly -4 hours from my own timezone (UTC-4 NY).  I'm going to try to chase down that path in the code to make sure I didn't do anything to mess up the time zone in your code.

**Comment by ITJusus** [comment]
Get this, when I change my computer's system time zone from New York (UTC -4/5) to London (UTC)...now Crypto_vba at least does pull the real latest prices (up to Now), but the prices labled 01:00 in the results are actually a perfect match for 21:00 in my real time zone.  It's like Crypt_vba is seeing my system time zone is UTC -4 and then it is somehow grabbing data that's 4 hours old and only up to 4 hours old (completely missing the last 4 hours of data in the results).

I'm using VB v6.5 (Excel 2007)...do you think this is causing the issue or is there something I can fix in the code to force Crypto_vba to pull the latest historical price data without being -4 hours behind?

**Comment by ITJusus** [comment]
I ruled out it being an issue with VB v6.5 (Excel 2007).  I ran the same code in VB v7.1 (Excel 2016) and it still outputs results for historical prices that are 4 hours old (missing the last 4 hours of historical prices and showing for the last hour what was actually 4 hours ago).

**Comment by ITJusus** [comment]
I was able to modify the Crypto_vba code's C_ARR_OHLCV function, adding the following line...

_If MaxTimeDate > DateSerial(2000, 1, 1) Then
    **MaxTimeDate = DateAdd("h", 4, MaxTimeDate) 'Custom TimeZone Change**
    dt = DateToUnixTime(MaxTimeDate)
    TimeTxt = "&toTs=" & dt_

Now I actually do get the last 4 hours of historical price data in my results, but the dates themselves are 4 hours in the future.  Trying to figure out how I can balance out this problem without having to add a lot of extra time to the processes having to re-update the date of each row in Excel each time I have to pull this data.  The best approach would be for Crypto_vba to get the correct data, aligned with the correct date, from the get go.

**Comment by ITJusus** [comment]
I was able to modify the Crypto_vba code's C_ARR_OHLCV function, adding the following line...

_If MaxTimeDate > DateSerial(2000, 1, 1) Then
    **MaxTimeDate = DateAdd("h", 4, MaxTimeDate) 'Custom TimeZone Change**
    dt = DateToUnixTime(MaxTimeDate)
    TimeTxt = "&toTs=" & dt_

Now I actually do get the last 4 hours of historical price data in my results, but the dates themselves are 4 hours in the future.  Trying to figure out how I can balance out this problem without having to add a lot of extra time to the processes having to re-update the date of each row in Excel each time I have to pull this data.  The best approach would be for Crypto_vba to get the correct data, aligned with the correct date, from the get go.
