### ISSUE TITLE
HitBTC in crypto_vba_example.xlsm

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#35]
Hi krijnsent,

I see in the comment that you added HitBTC v2 in the latest version of of the crypto_vba_example spreadsheet, however I don't see a HitBTC tab. Could you please add it to the spreadsheet when you get sometime, or let me know if I am missing something?

Many thanks

**Comment by krijnsent** [comment]
Noted, will try to add it.

**Comment by krijnsent** [comment]
@Pi-Rr Have added examples for all exchanges, please check and close this ticket if it works for you too :).

**Comment by Pi-Rr** [comment]
Amazing, thank you very much!
I will test that over the weekend and keep you posted.

**Comment by Pi-Rr** [comment]
Hi Koen,
I have tested the HitBTC tab and it works like a charm :)
Also, I love the new example spreadsheet, you have done a lot of work for all the exchanges, really nice!
Thank you very much!
