### ISSUE TITLE
Binance GetMyData() trow out of memory error

### ISSUE THREAD

**Issue by omidedipidizi** [krijnsent/crypto_vba#37]
First of all, tank you all for this awesome project !!

I just tried to used the program and got this error when i click on button which is linked to GetMyBinanceData() 

It's quite strange , because i got 32 GB of memory ..

Can somebody help please ?

![memory](https://user-images.githubusercontent.com/25254194/39601219-40eae210-4eef-11e8-96d5-af3b604ac13e.PNG)

**Comment by krijnsent** [comment]
Mmm, sounds weird. Does it happen every time you run the code? What office&Windows version are you using?
