### ISSUE TITLE
Coinspot

### ISSUE THREAD

**Issue by markbbell** [krijnsent/crypto_vba#4]
Hi Koen,
Many thanks for writing this code. It has been very helpful for me to learn how to make API calls.
However, I use www.coinspot.com.au and I'm unable to amend your script to work with their requirements.
Would you be able to have a look at creating one please?
They only have a single page on their website that details their API requirements - https://www.coinspot.com.au/api
Thanks, Mark.

**Comment by krijnsent** [comment]
Will look into it, have a couple of extra exchanges on my to-do list.

**Comment by krijnsent** [comment]
Hi Mark, I added the Coinspot API. The public one works, but the private one gives the same error as the PHP setup ("invalid"), like the issue in this project: https://github.com/jacobau/coinspot-php-client/issues/1
So I assume that their API changed somehow, will test again somewhere later.

**Comment by markbbell** [comment]
Thank you. Much appreciated.
I'm getting the invalid error as well. Look forward to the next update. Thanks,

**Comment by krijnsent** [comment]
Update: still have an issue, now am getting "nonce invalid", same error as this post of dec-2017 with the Coinspot reply that it's long overdue: https://stackoverflow.com/questions/47799323/coinspot-api-with-powershell

**Comment by krijnsent** [comment]
Updated and got it working.
