### ISSUE TITLE
Bittrex suddenly down

### ISSUE THREAD

**Issue by balin77** [krijnsent/crypto_vba#40]
Hey dude,

I use basically the same code for private Bittrex requests, but two days ago, it just stopped working. The only answer I receive is "Bad Request". I have no idea what the problem might be, since i have not changed the code. Could you have a look if you receive the same error?

**Comment by Pi-Rr** [comment]
Hi balin77,

I am getting the same issue with Bittrex, don't know what is causing it.

Hope someone will be able to help.

Cheers

**Comment by krijnsent** [comment]
Hi both,
I found it, the code has
objHTTP.Send (postdata)

Remove the last part:
objHTTP.Send

And it should work again.
I am updating my code, the module will be reworked a bit to catch this error better, as the Bittrex response was a bit more clear (no data allowed in the request body).

Cheers,

Koen

**Comment by balin77** [comment]
Hey Koen,

thank you very much for this solution. I wouldnt have found it in ages. 

a big thank you

balin

**Comment by Pi-Rr** [comment]
Thank you very much, the fix worked :)
