### ISSUE TITLE
All account balances not being pulled in from Bittrex

### ISSUE THREAD

**Issue by xspeedy300zx** [krijnsent/crypto_vba#41]
How do I pull all the wallet data from Bittrex including the empty wallets....I believe there are 210 of them. Currently the code is only pulling 83 of them. ADA to XVG only. How Do I fix this?

**Comment by krijnsent** [comment]
Hi @xspeedy300zx  , thanks for your feedback. I've tried it with my account, I get only 8 different currencies back. So it seems that the Bittrex API won't give back more (not all empty ones). 
So what you could do is first get all currencies, a public method (getcurrencies). And afterwards loop though the Private function getting the balance of every coin one at a time (getbalance)...
See their API documentation: https://support.bittrex.com/hc/en-us/articles/115003723911-Developer-s-Guide-API
