### ISSUE TITLE
Instructions on how to use it for Dummies 

### ISSUE THREAD

**Issue by Kogarius** [krijnsent/crypto_vba#44]
Hi and big thanks for this project.

I am an newbie using vba, so I would really appreciate it if you could add a simple instruction how to properly install and use this tool. 

Thx

**Comment by krijnsent** [comment]
Hi Kogarius,
there is nothing to install. What you can do is download the example xlsm file from the repository and start from there. On several sheets there are examples for exchanges to e.g. pull in your balances. Having said that, it's not a full fledged user-friendly tool yet. The project is basically rough building blocks. If you want to use them, you'd have to learn some VBA.
I'd recommend e.g. https://www.excel-easy.com/vba.html or http://homeandlearn.org/ if you want to give that a try.

Cheers,

Koen

**Comment by Kogarius** [comment]
Thx very much for your reply and the links.
I am glad that I found your project.

Keep up the good work and have a great day.

Kogsi

-------- Original-Nachricht --------
An 14. Jan. 2019, 09:46, Koen Rijnsent schrieb:
