### ISSUE TITLE
Kucoin update no longer working

### ISSUE THREAD

**Issue by Pi-Rr** [krijnsent/crypto_vba#45]
Hi Koen,

Kucoin has released a new version of its API and the macro to pull balance of our tokens is no longer working. Could you have a look and try to fix that in the crypto_vba_example.xlsm spreadsheet when you get a chance?

Many thanks!

**Comment by krijnsent** [comment]
Thanks, I've been noticed, finally got some basic building blocks up and running (e.g. my code to import/export bas files and Sourcetree vs Github desktop), so will start working on this in one of the coming days.

**Comment by Pi-Rr** [comment]
Super, thanks a lot :)

**Comment by krijnsent** [comment]
Should be working again, updated the code and the example in the sheet. Please close the issue when you've checked it works. You will have to create a new API key pair at KuCoin.

**Comment by Pi-Rr** [comment]
Thanks a lot Koen!
I am out this weekend but should be able to test Sunday evening. I'll
update the ticket after that.

Best

**Comment by Pi-Rr** [comment]
Hi there, tested the new example, works perfectly, thank you very much!
