### ISSUE TITLE
Binance cancel order

### ISSUE THREAD

**Issue by Dnanilem1** [krijnsent/crypto_vba#46]
Hello
I would like to cancel a buy or sell order on Binance, but I can not. thank you for giving me a track.
Purchase and sale orders work very well.
My command line
PrivateBinance("order", apikey, secretkey, "symbol=BNBUSDT&orderId=83375426&timestamp=" & Temps)
Error message
{"code":-1101,"msg":"Duplicate values for a parameter detected."}
A thousand excuses for English
Merci

**Comment by incobart** [comment]
Bonjour Dnanilem,
I think &timestamp=" & Temps should not be there  , and the DELETE function is not provided in this app. Koen will possibly add later.

**Comment by krijnsent** [comment]
Hi @Dnanilem1 and @incobart , could you check the latest code, it provides an example in the tests. If that's okay, please close this issue.

**Comment by Dnanilem1** [comment]
Merci pour votre aide.
Le code fonctionne très bien pour mon usage.
Thanks for your help.
The code works very well for my use.
