### ISSUE TITLE
Binance VBA Problem

### ISSUE THREAD

**Issue by ieselcuk** [krijnsent/crypto_vba#47]
Hi, 
When I execute Sub TestBinance() at crypto_vba_example.xlsm, I see an error at line 
"Test.IsOk JsonResult("balances").Count > 10" . The pop up says run time error 424 object required.
Thank you.

**Comment by krijnsent** [comment]
Hi,
After:
TestResult = PrivateBinance("account", "GET", Cred, Params2)
Can you add:
Debug.print TestResult
And check if there are balances in that result? The test runs smoothly at my PC.

**Comment by ieselcuk** [comment]
Thank you very very much. Best regards.
