### ISSUE TITLE
Kraken api doesn't work

### ISSUE THREAD

**Issue by job97** [krijnsent/crypto_vba#49]
Hello Koen,

I'm trying for days to get your code working although I'm not that experienced yet. My first aim was to get the Kraken api working but I got stuck and tried the Binance api. They both got errors while running the test routine. After your last update from 2 days ago the Binance api is working and the errors didn't show up in the the code. So I'm really happy with that:) 
The Kraken api is still not working for me. I figured out that the errors resolved when I changed the lines from the first to the second line.

Test.IsEqual JsonResult("error")(1), "EGeneral:Invalid arguments"
Test.IsEqual JsonResult("error"), (1), "EGeneral:Invalid arguments"

Test.IsOk JsonResult("result")("unixtime") >= 1510000000
Test.IsOk JsonResult("unixtime") >= 1510000000

Test.IsOk JsonResult("result")("XXBTZEUR") >= 1510000000
Test.IsOk JsonResult("XXBTZEUR") >= 1510000000

Test.IsOk JsonResult("result")("KFEE") >= 0
Test.IsOk JsonResult("KFEE") >= 0

Test.IsOk JsonResult("result")("trades").count >= 0
Test.IsOk JsonResult("trades") >= 0

But still the api connection doesn't work, see the error below: 
![kraken api](https://user-images.githubusercontent.com/5849705/55879623-5c6bb100-5b9f-11e9-8021-2b579c8fcaae.PNG)

Hope you can help me out!
Cheers:)

**Comment by krijnsent** [comment]
Hi @job97 
I just downloaded my crypto_vba_example.xlsm file and ran some code. Did you also download all of the latest code (also the other modules, as they are used in this code)?:

Sub TestKraken() ->
This code crashes when you have an invalid key pair for the exchange. That is because the API returns:

TestResult = PrivateKraken("Balance", "POST", Cred)
Debug.Print TestResult
->{"error_nr":200,"error_txt":"HTTP-OK","response_txt":{"error":["EAPI:Invalid key"]}}
The crash will happen at:
Test.IsOk JsonResult("result")("KFEE") >= 0

That is because of the way JsonConverter.ParseJson works, transforming the JSON text into a Dictionary. Basically, if you're looking for an item, e.g. Debug.Print JsonResult("bla") , that will always work and give back an empty result. If you try Debug.Print JsonResult("bla")("bla"), that will throw the error 13.

If I run STEP 1 of GetMyKrakenData, that works too, showing in B13:
{"error":[],"result":{"unixtime":1554912576,"rfc1123":"Wed, 10 Apr 19 16:09:36 +0000"}}

So could you try downloading the latest .xlsm example file and give that a swing?
Cheers,
Koen

**Comment by job97** [comment]
Hi Koen,

Yes, I did download the latest crypto_vba_example.xlsm file, and this is when the binance api started to work. I supposed that all other necessary code has been updated in this last .xlsm file?

I've tried it with an other api key pair, but got the same results. Do you think I need to adjust the nonce window? By default it's 0 (you can find this option by editing the api key on kraken). 

You said the I got this error because of an invalid key pair, but the first line where I get that error 13 is on this line:
Test.IsEqual JsonResult("error")(1), "EGeneral:Invalid arguments"

Which is relative to the public data, so why do I actually need this api key pair for public data?

Hope you have now a better view of my situation;)
Cheers

**Comment by krijnsent** [comment]
Hi there,
what MS Office version are you using? When I google for the error number in your screenshot I see that it might have to do with the WinHttpRequest that is made. That happens in ModWeb, the function WebRequestURL.
What you could try:
-check the references in the example file, make sure there is no "MISSING" reference
-add (if not there) Microsoft WinHTTP services, version 5.1
-if that doesn't help, try inserting a line in WebRequestURL:
Dim objHTTP As WinHttpRequest
(Direcly as first line.)

The easiest way to test the basics is to make a small sub with just 1 line of code:
Debug.Print PublicKraken("Time", "GET")
'That should give back e.g.: {"error":[],"result":{"unixtime":1551737935,"rfc1123":"Mon,  4 Mar 19 22:18:55 +0000"}}

Hope those pointers help,
Koen

**Comment by job97** [comment]
Hi Koen,

I''m using MS office 2016 and VB for applications 7.1 version 1087. I did check the references and to be sure I've added the line of code you mentioned. But still the strange thing is that other methodes than Kraken do give me a valid return, while they are using the same WebRequestURL methode.

When I debugged the code, I saw it goes wrong after sending the request (the line below).
objHTTP.Send 
Debug.Print Err.Number

The result is: -2147012739 
While the error number in the message as shown in my screenshot is -2147483638

Those are really strange things to me, but still hope you could help me out:)

Cheers,

**Comment by krijnsent** [comment]
Mmm, okay, we're focussing on the WebRequestURL function, as that seems to be the culprit.
Could you try adding some lines after the Set objHTTP? That basically forces some settings:

Set objHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")
'HTTP options, can be outcommented/changed if needed
'WinHttpRequestOption_SslErrorIgnoreFlags  - 13056: ignore all err, 0: accept no err
objHTTP.Option(4) = 13056
'WinHttpRequestOption_SecureProtocols - 512 = TLS 1.1, 2048 for TLS 1.2
objHTTP.Option(9) = 2048

And another option that might add something:
objHTTP.Open "GET", strURL -> Change to:
objHTTP.Open "GET", strURL, False

And another option that might add something:
objHTTP.Open strMethod, strURL -> Change to:
objHTTP.Open strMethod, strURL, False

Next try :)
Koen

**Comment by job97** [comment]
Hi Koen,

Thanks a lot for all your support!
Finally things starts to work!:)
I found out that I needed to add this line of code:
Set objHTTP = CreateObject("MSXML2.XMLHTTP")
Which I found in this link: https://devblogs.microsoft.com/scripting/how-can-i-tell-whether-a-web-page-is-accessible/

Also these two lines needed to be changed as you mentioned:
objHTTP.Open "GET", strURL -> Change to:
objHTTP.Open "GET", strURL, False

objHTTP.Open strMethod, strURL -> Change to:
objHTTP.Open strMethod, strURL, False

Now I get a valid response from the public request and my balances are shown on the kraken sheet. So everything looks working fine. The only strange thing is that, when I run the testKraken() routine it goes stuck on this line:
Test.IsOk JsonResult("result")("KFEE") >= 0
Giving back error 13. Do you know how this could be, while I still get my private balances back?

Cheers:)

**Comment by krijnsent** [comment]
Cool, that basically uses a different connection to get to the same URL. What is the result of:
Debug.Print TestResult (if you put that line above the line that gives an error message)?

**Comment by job97** [comment]
Yes! now it's working fine:)
The secret key was missing, cause for some reason the "secretKey" was changed in "secreKey". But in the original crypto_vba_example.xlsm file it is oke, so I might changed it accidentally. 

So now I'm using the first line, but what is actually the difference, I mean why didn't the second line work for me? And does the first line also work for you?

Set objHTTP = CreateObject("MSXML2.XMLHTTP")
Set objHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")

Thanks again for your advice:)

**Comment by krijnsent** [comment]
Hi @job97 
both work in my code, so I added that option to ModWeb, will push it with the next update. I have no idea why one connector/dll does work and the other doesn't. As far as I understood MSXML2 builds on the WinHttpRequest, so I don't know why that one wouldn't work.
Cheers

**Comment by job97** [comment]
Hi Koen,

Just got to know why the WinHttp.WinHttpRequest.5.1 didn't work for me. I'm using windows 7 and needed to install TLS 1.1 and TLS 1.2. After not being able to get right data from json using MSXML2.XMLHTTP, I was forced to dive into this problem. 

Installing all windows optional updates didn't work for me. Using the easy installer from windows which is free to download on this link:
https://support.microsoft.com/nl-nl/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi  
did do the job. So now I'm using WinHttp.WinHttpRequest.5.1 and everything is working perfectly fine. 

Cheers:)

**Comment by krijnsent** [comment]
@job97 Good to hear! Will have to make a section "troubleshooting & drivers" in my manual and add this. Out of curiousity: what are you building with my code?

**Comment by job97** [comment]
I'm creating a tool which automatically execute trades depending on the market data. This analysis will be done by Matlab. The tool also needs to keep an eye on money management etc. 
But this is still a demo, I might change the system using a database and python instead of vba and excel.
