### ISSUE TITLE
Basic code has import references unclear

### ISSUE THREAD

**Issue by titmy** [krijnsent/crypto_vba#50]
Hi,  have issues manually importing the vba references. Is there a way to do it automatically?

**Comment by krijnsent** [comment]
Hi @titmy , did you try downloading the example file (and afterwards deleting the modules you don't need), that file has the right references.
When I run this code in my develop tool ( https://www.wiseowl.co.uk/blog/s204/vbe-references.htm ), these are the references I have switched on:

VBA           Visual Basic For Applications             C:\Program Files (x86)\Common Files\Microsoft Shared\VBA\VBA7.1\VBE7.DLL
Excel         Microsoft Excel 16.0 Object Library       C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
MSForms       Microsoft Forms 2.0 Object Library        C:\WINDOWS\SysWOW64\FM20.DLL
Scripting     Microsoft Scripting Runtime C:\Windows\SysWOW64\scrrun.dll
VBIDE         Microsoft Visual Basic for Applications Extensibility 5.3             C:\Program Files (x86)\Common Files\Microsoft Shared\VBA\VBA6\VBE6EXT.OLB
MSHTML        Microsoft HTML Object Library             C:\Windows\SysWOW64\mshtml.tlb

**Comment by titmy** [comment]
Hey thanks for the prompt reply. Seems like my excel is not playing nicely, are there large objects being stored? right now I am having an out-of-memory error. test scripts are failing too with a error 
![image](https://user-images.githubusercontent.com/15183432/56218773-1aa7a280-6098-11e9-86b7-6ef023158f9b.png)

**Comment by krijnsent** [comment]
Hi there,
* at what line(s) does your code crash? 
* what excel/windows version are you using?
* did you use the excel example file or a self-imported version?
Cheers

**Comment by titmy** [comment]
Apologies for not adding the details. 

1.  Running macro ShtBinance.GetMyBinanceData or any other exchange macro just fails with out of memory doesnt show which line 
2. For test macro functions it fails here 
![image](https://user-images.githubusercontent.com/15183432/56220504-234da800-609b-11e9-98c2-2bd6a464f96d.png)

3. I am on Microsoft Excel for Office 365 MSO (16.0.11425.20200)) 64 bit

**Comment by krijnsent** [comment]
From this link: https://social.msdn.microsoft.com/Forums/en-US/9bfcd001-5168-4cff-b2ba-6b8e8d465138/excel-2010-vb-runtime-error-2146232576-80131700-automation-error-on?referrer=https://social.msdn.microsoft.com/Forums/en-US/9bfcd001-5168-4cff-b2ba-6b8e8d465138/excel-2010-vb-runtime-error-2146232576-80131700-automation-error-on

Quote:
I downloaded Microsoft .NET Framework 2.0 SP2 (which automatically also installed 3.5) at the same time, and the following code now works.  Much appreciate the suggestions from you and the forum board!

Here's the link to the download:  http://www.microsoft.com/en-us/download/confirmation.aspx?id=1639

**Comment by titmy** [comment]
Hey Krijinsent thanks for your help downloading the .NET framework works. Maybe you can put that as prerequisite in the docs

**Comment by krijnsent** [comment]
Updated the readme, closing the issue.
