### ISSUE TITLE
API limit reached (where API key stored)

### ISSUE THREAD

**Issue by ITJusus** [krijnsent/crypto_vba#52]
I've been running into an issue where the app stops pulling price data.  Once I'm in this state, when I go to the CryptoCompare api website (https://min-api.cryptocompare.com/)...I'm presented with a message similar to the following, rather than the normal webpage:

_{"Response":"Error","Message":"You are over your rate limit please upgrade your account!","HasWarning":false,"Type":99,"RateLimit":{"calls_made":{"second":1,"minute":1,"hour":44,"day":44,"month":2010716,"total_calls":2125796},"max_calls":{"second":50,"minute":1000,"hour":20000,"day":200000,"month":2000000}},"Data":{}}_

I eventually went ahead and generated my own API Key from the site (when I could access it again), but I don't know where I would plug my new API Key into the crypto_vba code.

Can you tell me if there is a way around getting stuck in this situation as well as where I might plugin my own API Key for CryptoCompare.?

**Comment by krijnsent** [comment]
Good point, I included it in the update I made for Cryptocompare. Could you check that code?

**Comment by ITJusus** [comment]
Thank you.  Closing ticket now.

**Comment by akshitv1** [comment]
Same issue. Was this resolved ?

**Comment by krijnsent** [comment]
It has been a while. In principle, the issue is solved. Are you using your own API key? How many queries are you running?

**Comment by akshitv1** [comment]
No, i guess you guys count the api calls using the ip address and not via api key. Correct me if i am wrong here. Yes i am using my own api key, calls just reached 50k.

**Comment by krijnsent** [comment]
> No, i guess you guys count the api calls using the ip address and not via api key. Correct me if i am wrong here. Yes i am using my own api key, calls just reached 50k.

I don't understand you. Who are "you guys"? I built the connector from Excel trough VBA to get data from crypto compare, using their API. They (cryptocompare) are responsible for their API infrastructure, so they are the ones limiting the number of usages and sending back the message that you've reached your limit. All my VBA code does is pass that message on to you. To contact them, see https://www.cryptocompare.com/ (contact link is at the bottom).
