### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by danideruiter** [krijnsent/crypto_vba#55]
Just a very dumb question. I opened the example excel sheet and under apikey and secretkey (Binance tab) I entered my Binance generated keys but nothing happens. All balances remain zero and even epoch time doesn’t change. What I’m doing wrong? I run windows 10 with excel 2013

**Comment by krijnsent** [comment]
Hi @danideruiter , sorry I missed your question. What you'd need to do is to run the right macro: GetMyBinanceData in the sheet ShtBinance. You could either go to ALT+F8 (macros) or VBE: ALT+F11 and start that macro. The tool itself does require a bit of knowledge of VBA: it's like a pack of lego blocks, not the finished construction :).
