### ISSUE TITLE
Bittex V3 implementation

### ISSUE THREAD

**Issue by hammerjoe** [krijnsent/crypto_vba#57]
Bittrex has announced that they will stop supporting V1 in September with the release of their V3 Api.

Are there any plans to add support for V3?

**Comment by krijnsent** [comment]
Now there is. My development is mainly demand driven, so will have a look at the new API. Thanks for the update

**Comment by hammerjoe** [comment]
I was just wondering if the new v3 for bittrex will be implemented? I think Bittrex will stop v1 at the end of the month.
Thanks for your work.

**Comment by krijnsent** [comment]
Just updated Bittrex, public API works, private API partially (without extra parameters). Will hopefully get it to work soonish.

**Comment by krijnsent** [comment]
Please test the latest version, it should work with v3. If it works, do feel free to close this issue.

**Comment by hammerjoe** [comment]
Thank you very much for your work. Its awesome.
