### ISSUE TITLE
Error In CryptoCompare rates

### ISSUE THREAD

**Issue by Nikhil9999176167** [krijnsent/crypto_vba#60]
Hi Developer,

Thanks for creating a great tool. It could have save a lot of time. I however found that Rates in CryptoCompare API are not reflective of actual rates and the API gives any rates. 

USD to INR for reference, if you populate the USD INR conversion provided by the API, it appears that the rates are not good. It returns more that 80 on a few days which has never happened. On a few other days, it returns more than 100. 

Maybe we need to flag this to CryptoCompare that the rates are inaccurate. I thought to inform you because you created the code and I am not sure how the API works and you may be the best judge based on the problem explained.

**Comment by krijnsent** [comment]
Thanks for your feedback. I will have a look and see if I can send Cryptocompare some feedback. I have some more price issues with their data, so can include them too. Will post it if i get an answer.

**Comment by Nikhil9999176167** [comment]
Thanks a lot dear and hreat work overall :).

Can you additionally send an email if possible to me if they respond?

**Comment by krijnsent** [comment]
Sorry, no answer from them. Closing this issue for now.
