### ISSUE TITLE
Bitvavo

### ISSUE THREAD

**Issue by matieke** [krijnsent/crypto_vba#69]
I would like to see Bitvavo added to this project. There are currently no portfolio management apps that use the bitvavo API for live transaction syncing. 

https://docs.bitvavo.com/

**Comment by krijnsent** [comment]
Will have a look at them, thanks for the suggestion.

**Comment by krijnsent** [comment]
Hi @matieke, can you test the code? I added BitVavo including a small example in the example xlsm file. If it works, please close this issue. Thanks!
