### ISSUE TITLE
What about Coinbase or GDAX?

### ISSUE THREAD

**Issue by theMoe** [krijnsent/crypto_vba#7]
Could you please add Coinbase and GDAX?

https://developers.coinbase.com/

https://docs.gdax.com/

**Comment by krijnsent** [comment]
Just created an account with Coinbase, although they seem to have a hard time recognizing my passport/drivers license. Will work on it when that gets sorted out.

**Comment by krijnsent** [comment]
Added the public API. Have been trying a couple of times to upload my drivers license and passport, but to no avail. Their approval system kind of sucks and they state that it's not worth contacting them about it as they are too busy with all the new customers.

**Comment by krijnsent** [comment]
Added the private API too, please check and close this issue if it works.

**Comment by theMoe** [comment]
@krijnsent Thanks for your work! I will check it out. Have you looked at the API of Coinbase? Or can I reach coinbase accounts via GDAX API?

**Comment by krijnsent** [comment]
@theMoe Nope, haven't looked at Coinbase yet, it looked like GDAX was their trading platform. They seem somehow connected, but not really. Will dive into it some day.

**Comment by fatkidz4** [comment]
Hi krijnsent,
Excellent work on this project, you deserve coffee and a beer.   I am having trouble posting an order to GDAX.  I using the body:
{"price": "1000.00","size": "0.01","side": "buy","product_id": "BTC-USD"}

Excerpt from Function PrivateGDAX:
SignMsg = NonceUnique & UCase(HTTPMethod) & "/" & Method & body

Any ideas what I am doing wrong?

**Comment by krijnsent** [comment]
Hi @fatkidz4 and @theMoe Can you test the new API? I built both a Coinbase and CoinbasePro/GDAX version and my tests are successfull. Please check and close this issue if it works for you too.

**Comment by krijnsent** [comment]
Has been over a month, closing issue
