### ISSUE TITLE
Trojan:Script/Oneeva.A!ml Windows Defender

### ISSUE THREAD

**Issue by kaiznet** [krijnsent/crypto_vba#73]
Hi! first thanks to anyone who has made a contribution to this repository. I was about to play around it a little bit, when I stumbled upon this Windows Defender alert "Trojan:Script/Oneeva.A!ml" that quarentined xlsm example file.

Any ideas why is this happening?

Thanks!

**Comment by krijnsent** [comment]
Hi there, #67 has the same issue... TBH: I don't have the issue and don't know how to solve it, as my excel example is updated every now and than. I added a bit in the readme: you could import the bas modules you need one-by-one...

**Comment by emmanuelvi** [comment]
Hi, I had exactly the same issue, downloading the ZIP file. 
I've solved like this: 

- I have download the Github desktop app : https://desktop.github.com/
- Then cloned the repository "URL": 
- Then all files are there in my local folder.

**Comment by krijnsent** [comment]
Thanks @emmanuelvi !
I'm going to close this issue: I know it's there but can't do anything about it. I've put 2 work arounds in my readme.md including yours with github desktop.
