### ISSUE TITLE
CoinbasePro all fills

### ISSUE THREAD

**Issue by birth23** [krijnsent/crypto_vba#74]
How to list all filled orders in an CoinbasePro account?  Is there a way to export a list of all transactions without specifying the product_id?

**Comment by krijnsent** [comment]
Hi there,
issue #72 has some code to help you with some VBA for that request (with my reply with that isssue). And if you look at https://docs.pro.coinbase.com/#fills , they state "You are required to provide either a product_id or order_id.", so no, that's not possible with their API, you'll have to loop through all products or orders one by one.
Cheers,
Koen
