### ISSUE TITLE
Definition of some functions

### ISSUE THREAD

**Issue by fariborz1221** [krijnsent/crypto_vba#76]
I would appreciate if you could let me know where I can find the following  functions definition:
WebRequestURL(...
DictToString(...

**Comment by krijnsent** [comment]
Hi there,

I hope you already checked out the code?
WebRequestURL is in ModWeb , there are quite some examples in the test procedure at the top of the module. What it basically does is throw a request to a web server. That could be a GET, POST, etc request (strMethod parameter) and the function allows you to e.g. add headers to the web request. It will always return JSON.

DictToString is in ModFunctions, the test cases at the top of the module show how it can be used. What it basically does: translate a dictionary object into a string. That's practical to e.g. get the JSON or URL required for a web request.

Hope that helps,
Koen

**Comment by fariborz1221** [comment]
Hi,

Thank you very much for taking the time to answer my question. Somehow I
had perceived that your codes are using Python to make requests. I wanted
to get the cryptocurrency ticker prices from Binance. I will learn a lot
from your way of coding.

Regards,

Fariborz Rafati

**Comment by krijnsent** [comment]
Nope, all this code is pure VBA :-)

**Comment by fariborz1221** [comment]
Thank you very much
