### ISSUE TITLE
Error in Sub TestBitVavo()

### ISSUE THREAD

**Issue by jeroen-githu** [krijnsent/crypto_vba#77]
When running the .bas file TestBitVavo(),  the error 'datatype not defined' in line 'Dim Suite As New TestSuite'

The references you mentioned are set.

What could be the issue ?

thanks,
jeroen

**Comment by krijnsent** [comment]
You probably didn't import the classes (.cls files in the repository)?

**Comment by jeroen-githu** [comment]
Many thanks, I continued with the example file.
