### ISSUE TITLE
error -1100 Illegal characters found in parameter 'timestamp'; legal range is '^[0-9]{1,20}$'.

### ISSUE THREAD

**Issue by deciBel1982** [krijnsent/crypto_vba#8]
Hi there,
It's strange. When I try the code after midnight it no longer works and throws this error on any type of API call via VBA.
I can't say till what timestamp this issue occurs, becasuse when I tested this morning it worked again.
For info, I'm on CET+1h
Nice work by the way.
KR;,
Bart

**Comment by deciBel1982** [comment]
I believe it has got something to do with the Timer part in the code....
NonceUnique = NonceUnique + TimeCorrection & Right(Timer * 100, 2) & "0"

**Comment by krijnsent** [comment]
Hi deciBel1982, I assume you are talking about the Binance API connector? I am getting the same response, will dive into it.

**Comment by deciBel1982** [comment]
Hi Koen, yes, I'm sorry if I was not clear.
Interesting, after 3u00 (again, GTM+1h) it seems to work again.

**Comment by krijnsent** [comment]
Binance API connector now working. The issue was an extra space in the timestamp code (which was the illegal character).

**Comment by krijnsent** [comment]
Binance API connector now working. The issue was an extra space in the timestamp code (which was the illegal character).

**Comment by kinoli** [comment]
I'm getting this same message. I'm using node-binance-api v0.4.24.

**Comment by krijnsent** [comment]
Hi @kinoli , are you using my VBA macros or the NodeJS code? If it's that latter, please post the error there: https://github.com/jaggedsoft/node-binance-api

**Comment by kinoli** [comment]
NodeJS, but I don't seem to be getting it anymore. Not sure what happened exactly.
