### ISSUE TITLE
Virus included in the download

### ISSUE THREAD

**Issue by aroxo** [krijnsent/crypto_vba#84]
I am getting a virus alert from the download. It is a specific virus, rather than just a general issue surrounding an xlsm. I work with Macro enabled Excel spreadsheets all the time, so I think it's not that.

This is what I am seeing:

![image](https://user-images.githubusercontent.com/1679870/134665650-7ec8f911-7ef3-402f-8ea4-6b3d85baa4de.png)

And this in Chrome:

![image](https://user-images.githubusercontent.com/1679870/134665674-60afa574-039e-48fb-b40f-a12cc81fc00e.png)

Matt.

**Comment by krijnsent** [comment]
Hi there, please check out the readme, this issue is described there...
