### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by Gerhard15** [krijnsent/crypto_vba#87]
Hello... Sorry i don't know if it's a issue by you. But i can't download the example file... i always get an network error!?

How can I download the example file!?

Please help me - thx

**Comment by krijnsent** [comment]
Hi @Gerhard15 ,
that's weird, it downloads for me (tried with a private browser window). Did you try the trick here: https://github.com/krijnsent/crypto_vba#virus-warnings ? It could be that your firewall/antivirus blocks it?
Just guessing... Maybe try on your mobile phone, see if it downloads there.
Cheers

**Comment by Gerhard15** [comment]
thx.. donwloading by mobilephone was ok.. but now i get an error  !?
![image](https://user-images.githubusercontent.com/86608008/143570984-bb19734b-cd04-4b8e-b8a9-49690ff8204b.png)

**Comment by krijnsent** [comment]
Sure, go ahead, my site is in my github profile. info@ that site will get your mail to me.

**Comment by Gerhard15** [comment]
is this the right EMail Address? info@castoro.nl
