### ISSUE TITLE
Could you add Cex.io, please?

### ISSUE THREAD

**Issue by bmgs1905** [krijnsent/crypto_vba#9]
Hello,

Thank you very much for this excel file.  It is very useful and  helpful for me. 

Could you add Cex.io, please?

Kind Regards,

BM

**Comment by krijnsent** [comment]
Hi BM, will put it on my to-do list, but have some other stuff to do first.

**Comment by bmgs1905** [comment]
Thank you very much.

**Comment by HansSheller** [comment]
Hi,

Is there any chance that CEX.io will be added in the short term?

I tried myself and while it works for public calls, I cannot make it work for private calls. I keep getting "API key is missing" as a response. I am sending the key, signature and nonce, but it seems like the API is somehow not receiving them :(

Thank you very much.

Kind regards,

**Comment by krijnsent** [comment]
Hi @HansSheller , i plan to give this a swing when i am near a computer, but am travelling without it for the coming period. August is my best guess

**Comment by HansSheller** [comment]
Hi @krijnsent ,

Thank you for the response. That would be more than great! :D 

I will be looking forward to it. Have an excellent week. Kind regards,

**Comment by krijnsent** [comment]
Ticket check: still looking for me to add cex.io ?

**Comment by bmgs1905** [comment]
No, thank you very much.

**Comment by P0u1us** [comment]
For all those lost souls in CEXio cyberspace (like me ;-), whom are trying to figure out how the CEXio API works… here is the golden nugget!
Contrary to most APIs, the CEXio API does NOT pass parms on with the HTTPS:// string !!!
The only variables used in the https:// string are the BasePair, eg: BTC, LTD, USD etc

ALL parameters are composed inside a single JSON string and passed when sending the object.http call: object.send “parms” !!!
Thus: 
Dim httpObj As New WinHttp.WinHttpRequest
httpObj.Open "POST", “https://cex.io/api/balance/”, False
httpObj.SetRequestHeader "User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)"
httpObj.SetRequestHeader "Content-type", "application/json"
etc
httpObj.send “{"key": "HLixH1aYdOIWOoRyoHkFpHlawrM","signature":"0BDEDB9339DCE83D46F09A1527663762B52C8B12BCD1910E685BEAFEEABECFF9","nonce":"1513175715"}”

As for the HMAC-SHA256: that is a composition of: “nonce”&”accountname”&”apikey”
Remember that the HASH must be UpperCase!
This has taken 3 days of my life ;-)

**Comment by krijnsent** [comment]
Hi @P0u1us , welcome to the club of trial-and-error. I remember my first exchange, that also took me days of frustration. Will see if I can build your example into code. If I do, can you test it for me?
Thanks,
Koen

**Comment by P0u1us** [comment]
Hoi Koen, Ik zou wel willen helpen, maar denk dat mij de benodigde expertise ontbreekt, ben zelf een oldskool hobbyist ;-) ik ben alles zelf aan het opbouwen en spiekt dan geregeld in jouw routines voor functies die ik niet helemaal door heb. maar laten we kontakt houden.

**Comment by P0u1us** [comment]
Hi Koen, if you were curious as to what I am doing with the code, then you could have a look at the following ;-)  https://github.com/P0u1us/TIDnow

**Comment by krijnsent** [comment]
Hi @P0u1us , thanks for the link! Looks like a tool I could use myself, although I'm not a trader. (Or rather: learned that I'm a crappy trader and should stick to excel.)

**Comment by P0u1us** [comment]
;-) I know that feeling/experience; and believe me: most are having the same result! very few have the random luck to do better! unless you are a whale who manipulates the market with sheer quantity.

**Comment by krijnsent** [comment]
Closing the issue due to inactivity, if you still have an issue/question, please open a new one.
