### ISSUE TITLE
API from Exchange MECX to be used in vba MsExcel

### ISSUE THREAD

**Issue by Hans195204** [krijnsent/crypto_vba#91]
Is there any ModExch compatable to use with MECX. 
I want to import my trades and closing prices in MsExcel using the API in VBA with an HTTP-request. For other Exchanges I got all working.

I have tried a lot but still getting error message: {"error_nr":400,"error_txt":"HTTP-Bad Request","response_txt":{"code":700004,"msg":"Mandatory parameter 'signature' was not sent, was empty/null, or malformed."}}.

Have someone already find out the header and the params for MEXC as I cannot figure out what is required and where to use?

Thanks

**Comment by krijnsent** [comment]
Hi @Hans195204 , that message states that the signature is missing from your message. If you look at their API-documentation:
https://mexcdevelop.github.io/apidocs/spot_v3_en/#signed

So with this example:
symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=1&price=11&recvWindow=5000&timestamp=1644489390087

They use that input plus a secretKey to calculate a signature: 323c96ab85a745712e95e63cad28903dd8292e4a905e99c4ee3932023843a117 (in that example)

So the total command that gets sent to the server:

$ curl -H "X-MEXC-APIKEY: mx0aBYs33eIilxBWC5" -X POST 'https://api.mexc.com/api/v3/order' -d 'symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=1&price=11&recvWindow=5000&timestamp=1644489390087&signature=323c96ab85a745712e95e63cad28903dd8292e4a905e99c4ee3932023843a117'

I'm assuming you're sending the command without the signature part added to it. Hope that helps adjusting any of the other Exch examples.

**Comment by Hans195204** [comment]
I use the following code to get the "account"-details:
Sub Mexc_account()

access_key = "xxx"
secret_key = "yyy"

Dim Params As New Dictionary
Dim Credents As New Dictionary

Credents.Add "X-MEXC-APIKEY", access_key
Credents.Add "X-MEXC-secretKEY", secret_key

Params.Add "X-MEXC-APIKEY", access_key
Params.Add "X-MEXC-secretKEY", secret_key
Params.Add "Content-Type", "application/json"
JsonResp = PrivateMexc("account", "GET", Credents, Params)
End Sub

Function PrivateMexc(Method As String, ReqType As String, Credentials As Dictionary, Optional ParamDict As Dictionary) As String

Dim MethodParams As String
Dim postdata As String
Dim url As String

TradeApiSite = "https://api.mexc.com"
ApiEndPoint = "/api/v3/" & Method
postdata = ""

servertijd = Mexc_DataOphalen("tijd", "", "")

If UCase(ReqType) = "POST" Then
    postdata = JsonConverter.ConvertToJson(ParamDict)
    If postdata = "{}" Then postdata = ""
ElseIf UCase(ReqType) = "GET" Or UCase(ReqType) = "DELETE" Or UCase(ReqType) = "PUT" Then
    MethodParams = DictToString(ParamDict, "URLENC")
    If MethodParams <> "" Then MethodParams = "?" & MethodParams
    ApiEndPoint = ApiEndPoint & MethodParams
End If

to_sign = Credentials("X-MEXC-APIKEY") & servertime & MethodParams & Credentials("X-MEXC-secretKEY")

signA = ComputeHash_C("SHA256", to_sign, "STRHEX")


url = TradeApiSite & ApiEndPoint

Dim UrlHeaders As New Dictionary
UrlHeaders.Add "X-MEXC-APIKEY", Credentials("X-MEXC-APIKEY")
UrlHeaders.Add "Authorization", Credentials("X-MEXC-secretKEY")
UrlHeaders.Add "X-MEXC-API-Signature", signA
UrlHeaders.Add "recvWindow", 50000

PrivateMexc = WebRequestURL(url, ReqType, UrlHeaders, postdata)

Debug.Print PrivateMexc
End Function

'melding: {"error_nr":400,"error_txt":"HTTP-Bad Request","response_txt":{"code":700004,"msg":"Mandatory parameter 'signature' was not sent, was empty/null, or malformed."}}

As you see I send the signature and still got the error-message.
Thanks in advance for your help

**Comment by krijnsent** [comment]
I don't have access to their site, but I see some issues with your code. Currently, you're sending over your secret key, do never do that... You just use that secretkey to encrypt the message locally. I modified your code a bit, hopefully this helps (completely untested).


```
Sub Mexc_account()

access_key = "xxx"
secret_key = "yyy"

Dim Params As New Dictionary
Dim Credents As New Dictionary

Credents.Add "X-MEXC-APIKEY", access_key
Credents.Add "X-MEXC-secretKEY", secret_key

JsonResp = PrivateMexc("account", "GET", Credents, Params)

End Sub

Function PrivateMexc(Method As String, ReqType As String, Credentials As Dictionary, Optional ParamDict As Dictionary) As String

Dim MethodParams As String
Dim postdata As String
Dim url As String

TradeApiSite = "https://api.mexc.com"
ApiEndPoint = "/api/v3/" & Method
postdata = ""

servertijd = Mexc_DataOphalen("tijd", "", "")
ParamsDict.Add "timestamp", servertijd

If UCase(ReqType) = "POST" Then
    postdata = JsonConverter.ConvertToJson(ParamDict)
    If postdata = "{}" Then postdata = ""
ElseIf UCase(ReqType) = "GET" Or UCase(ReqType) = "DELETE" Or UCase(ReqType) = "PUT" Then
    MethodParams = DictToString(ParamDict, "URLENC")
    If MethodParams <> "" Then MethodParams = "?" & MethodParams
    ApiEndPoint = ApiEndPoint & MethodParams
End If

to_sign = MethodParams
signA = ComputeHash_C("SHA256", to_sign, Credentials("X-MEXC-secretKEY"), "STRHEX")

url = TradeApiSite & ApiEndPoint & "signature=" & signA
debug.print url

Dim UrlHeaders As New Dictionary
UrlHeaders.Add "X-MEXC-APIKEY", Credentials("X-MEXC-APIKEY")
UrlHeaders.Add "Content-Type", "application/json"
UrlHeaders.Add "recvWindow", 50000
PrivateMexc = WebRequestURL(url, ReqType, UrlHeaders, postdata)

Debug.Print PrivateMexc

End Function
```

**Comment by Hans195204** [comment]
Thanks for looking after my problem, but still getting the same message. I will further test the added code.
For your information: You can find the api documentation of Mexc on github.io  
Link : https://mexcdevelop.github.io/apidocs/spot_v3_en/#introduction
